[package]
name = "recolored"
description = "A fork of colored: the most simple way to add colors in your terminal"
version = "1.9.3"
authors = ["Thomas Wickham <mackwic@gmail.com>, Thomas Forgione <thomas@forgione.fr>"]
license = "MPL-2.0"
homepage = "https://github.com/tforgione/colored"
repository = "https://github.com/tforgione/colored"
readme = "README.md"
keywords = ["color", "string", "term", "ansi_term", "term-painter"]

[features]
# with this feature, no color will ever be written
no-color = []

[dependencies]
atty = "0.2.11"
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
default-features = false
features = [
    "consoleapi",
    "processenv",
    "winbase"
]

[dev_dependencies]
ansi_term = "0.12"
rspec = "=1.0.0-beta.3"
